### ISSUE TITLE
Add mysql support

### ISSUE THREAD

**Issue by CodeShakingSheep** [flathub/org.freedesktop.Sdk.Extension.php83#23]
Is it possible to add support for the following extensions?

- mysqli
- pdo_mysql

Thanks.

**Comment by Lctrs** [comment]
Why do you need them ? This extension is only meant to be able to run static analysis or LSP tools locally.

**Comment by CodeShakingSheep** [comment]
Because I want to be able to run a PHP web app from flatpaked VSCodium which uses a MySQL DB. As of now I can develop the app from VSCodium but I cannot start it with VSCodium run configuration or from VSCodium's integrated terminal. (It starts fine if I run it from a system terminal outside of VSCodium.)

**Comment by francoism90** [comment]
@CodeShakingSheep Are you using Laravel or any other framework using Docker?

https://github.com/amir9480/vscode-laravel-extra-intellisense#sample-config-to-use-docker

It is possible to use the PHP command of a Docker. I tried using a toolbox, but it isn't that easy to configure. You can link to an external terminal in vscode, and add your PHP extensions. But this workarounds the Docker sandbox.
