### ISSUE TITLE
How to install extensions?

### ISSUE THREAD

**Issue by francoism90** [flathub/org.freedesktop.Sdk.Extension.php83#9]
For my projects, I need additional PECL extensions like `phpredis` or even PHP included ones.

I know you can build the image yourself, but since this is a SDK, couldn't you just expose `sh`, and do something like:
```bash
flatpak run org.freedesktop.Sdk.Extension.php83 pecl install redis
```

Thanks

**Comment by Lctrs** [comment]
You can't. Flatpak is immutable.
